name: TabNet
classifier:
  estimator:
    _target_: pytorch_tabnet.tab_model.TabNetClassifier
  multioutput: false
regressor:
  estimator:
    _target_: fseval.estimators.tabnet.TabNetRegressor
  multioutput: true
estimates_feature_importances: true
estimates_target: false