on: push

name: mypy check

jobs:
  check:
    runs-on: ubuntu-latest
    container: baguasys/bagua:latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/mypy-check@master
        with:
          path: 'bagua'
