
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T23:31:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6a1a6c4502a1dc21cfc1da51ed096a5899d884ef",
 "version": "0.8.306"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
