
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-28T16:08:03+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e01291bb2668611a1bf7bcfa6829d195331aa6dc",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
