[tool.poetry]
authors = ["Darkflame72 <leon@bowie-co.nz>"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Natural Language :: English",
  "Framework :: AsyncIO",
  "Operating System :: OS Independent",
  "Topic :: Games/Entertainment",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]
description = "Asyncpixel"
documentation = "https://asyncpixel.readthedocs.io"
homepage = "https://github.com/Obsidion-dev/asyncpixel"
license = "GPLv3"
name = "asyncpixel"
readme = "README.md"
repository = "https://github.com/Obsidion-dev/asyncpixel"
version = "1.1.1"

[tool.poetry.dependencies]
aiohttp = "^3.6.2"
importlib_metadata = {version = ">=2,<5", python = "<3.8"}
pydantic = "^1.7.3"
python = "^3.7"
deprecation = "^2.1.0"

[tool.poetry.dev-dependencies]
Pygments = "^2.9.0"
aioresponses = "^0.7.2"
black = "^21.6b0"
coverage = {extras = ["toml"], version = "^5.5"}
darglint = "^1.8.0"
flake8 = "^3.9.2"
flake8-annotations = "^2.6.2"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
flake8-rst-docstrings = "^0.2.3"
mypy = "^0.910"
nox = "^2021.6.12"
nox-poetry = "^0.8.6"
pep8-naming = "^0.11.1"
pre-commit = "^2.13.0"
pre-commit-hooks = "^4.0.1"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
recommonmark = "^0.7.1"
reorder-python-imports = "^2.5.0"
safety = "^1.10.3"
sphinx = "^4.0.2"
sphinx-autobuild = "^2021.3.14"
sphinx-autodoc-typehints = "^1.12.0"
sphinx-rtd-theme = "^0.5.2"
typeguard = "^2.12.1"

[tool.coverage.paths]
source = ["asyncpixel"]

[tool.coverage.run]
branch = true
source = ["asyncpixel"]

[tool.coverage.report]
fail_under = 91
show_missing = true

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
