# Generated by Django 2.2.18 on 2021-05-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0013_auto_20201015_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control']},
        ),
        migrations.AddField(
            model_name='poll',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.URLField(default='https://unpkg.com/@startinblox/component-poll@2.1/img/defaultpoll.png', verbose_name='Illustration'),
        ),
    ]
