# Generated by Django 2.0.13 on 2021-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20201231_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessagingtemplates',
            name='category',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('INVESTMENT', 'Investment'), ('MANAGEMENT', 'Management'), ('MARKETING', 'Marketing'), ('SUPPORT', 'Support'), ('PROPERTY', 'Property'), ('ETC', 'Etc.')], default='ETC', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='messagingtemplates',
            name='category',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('INVESTMENT', 'Investment'), ('MANAGEMENT', 'Management'), ('MARKETING', 'Marketing'), ('SUPPORT', 'Support'), ('PROPERTY', 'Property'), ('ETC', 'Etc.')], default='ETC', max_length=50, verbose_name='Category'),
        ),
    ]
