# Generated by Django 2.0.13 on 2021-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20210311_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessagingtemplates',
            name='category',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('INVESTMENT', 'Investment'), ('MANAGEMENT', 'Management'), ('MARKETING', 'Marketing'), ('SUPPORT', 'Support'), ('PROPERTY', 'Property'), ('PAYMENT_REQUEST', 'Payment Request'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('ETC', 'Etc.')], default='ETC', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='messagingtemplates',
            name='category',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('INVESTMENT', 'Investment'), ('MANAGEMENT', 'Management'), ('MARKETING', 'Marketing'), ('SUPPORT', 'Support'), ('PROPERTY', 'Property'), ('PAYMENT_REQUEST', 'Payment Request'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('ETC', 'Etc.')], default='ETC', max_length=50, verbose_name='Category'),
        ),
    ]
