
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T16:55:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8bebc87436cec9ce48ff8700dd30aa176908dad",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
