
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T18:00:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "982fbafe115a8a1888a2d4508216931824ccd0bf",
 "version": "v0.2.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
