# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: th2_grpc_conn/conn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='th2_grpc_conn/conn.proto',
  package='conn',
  syntax='proto3',
  serialized_options=b'\n\032com.exactpro.th2.conn.grpcP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18th2_grpc_conn/conn.proto\x12\x04\x63onn\"\x0e\n\x0cStartRequest\"\x1c\n\x0bStopRequest\x12\r\n\x05\x61\x66ter\x18\x01 \x01(\r\"f\n\x08Response\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.conn.Response.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32^\n\x04\x43onn\x12+\n\x05start\x12\x12.conn.StartRequest\x1a\x0e.conn.Response\x12)\n\x04stop\x12\x11.conn.StopRequest\x1a\x0e.conn.ResponseB\x1e\n\x1a\x63om.exactpro.th2.conn.grpcP\x01\x62\x06proto3'
)



_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='conn.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=148,
  serialized_end=182,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)


_STARTREQUEST = _descriptor.Descriptor(
  name='StartRequest',
  full_name='conn.StartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=48,
)


_STOPREQUEST = _descriptor.Descriptor(
  name='StopRequest',
  full_name='conn.StopRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='after', full_name='conn.StopRequest.after', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=78,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='conn.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='conn.Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='conn.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=182,
)

_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE_STATUS.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['StartRequest'] = _STARTREQUEST
DESCRIPTOR.message_types_by_name['StopRequest'] = _STOPREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'th2_grpc_conn.conn_pb2'
  # @@protoc_insertion_point(class_scope:conn.StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

StopRequest = _reflection.GeneratedProtocolMessageType('StopRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPREQUEST,
  '__module__' : 'th2_grpc_conn.conn_pb2'
  # @@protoc_insertion_point(class_scope:conn.StopRequest)
  })
_sym_db.RegisterMessage(StopRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'th2_grpc_conn.conn_pb2'
  # @@protoc_insertion_point(class_scope:conn.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_CONN = _descriptor.ServiceDescriptor(
  name='Conn',
  full_name='conn.Conn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=184,
  serialized_end=278,
  methods=[
  _descriptor.MethodDescriptor(
    name='start',
    full_name='conn.Conn.start',
    index=0,
    containing_service=None,
    input_type=_STARTREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='stop',
    full_name='conn.Conn.stop',
    index=1,
    containing_service=None,
    input_type=_STOPREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONN)

DESCRIPTOR.services_by_name['Conn'] = _CONN

# @@protoc_insertion_point(module_scope)
