[tool.poetry]
name = "dupesearch"
version = "0.1.0"
description = ""
authors = ["wookie184 <wookie1840@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.4.0"
maturin = "^0.10.6"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

