# Generated by Django 3.1.10 on 2021-05-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20210111_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='moloformsubmission',
            name='is_shortlisted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='moloformsubmission',
            name='is_winner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
