
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-11T15:11:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbd37ed42dc8ea4fa8af32282918b65e56f51673",
 "version": "9.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
