
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-02T19:49:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "75f6b8a21a872e11950b0fe19a1ac9efac32bf6e",
 "version": "0.4.56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
