CGX_STREAM_ATTR = '2456E1B9-26E2-8F83-E744-F34F01E9D703'
CGX_TAIL_LENGTH_BYTES = 4
CGX_HEADER_LENGTH_BYTES = 2 - 1 # Ignored sync byte
CGX_CHANNEL_COUNT = 11
CGX_PAYLOAD_LENGTH_BYTES = CGX_CHANNEL_COUNT*3

CGX_PACKET_LENGTH_BYTES = CGX_HEADER_LENGTH_BYTES+CGX_PAYLOAD_LENGTH_BYTES+CGX_TAIL_LENGTH_BYTES
CGX_OFFSET_TAIL_BYTES = CGX_HEADER_LENGTH_BYTES + CGX_PAYLOAD_LENGTH_BYTES