# Generated by Django 2.0.13 on 2021-02-23 07:23

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySubscriptionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Filter Title')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=50, verbose_name='Status')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254, verbose_name='Emails'), default=list, size=None)),
                ('filter', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Filter')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Last Sent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
