# Generated by Django 2.0.13 on 2019-09-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190921_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'RENT'), ('deposit', 'DEPOSIT')], default='rent', max_length=30),
        ),
    ]
