# Generated by Django 2.0.13 on 2019-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rentpayment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'CREDIT_CARD'), ('DEBIT_CARD', 'DEBIT_CARD'), ('UNKNOWN', 'UNKNOWN')], max_length=30, null=True),
        ),
    ]
