# Generated by Django 2.0.13 on 2019-09-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rentpayment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='payment_made_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
