# Generated by Django 2.0.13 on 2019-10-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20191019_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransfers',
            name='application_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
