# Generated by Django 2.0.13 on 2019-11-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paymenttransfers_application_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'CREDIT_CARD'), ('DEBIT_CARD', 'DEBIT_CARD'), ('ACH_DEBIT', 'ACH_DEBIT'), ('UNKNOWN', 'UNKNOWN')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], max_length=30),
        ),
    ]
