# Generated by Django 2.0.13 on 2020-07-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_historicalpaymenttransfers_historicalrentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrentpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'CREDIT CARD'), ('DEBIT_CARD', 'DEBIT CARD'), ('ACH_DEBIT', 'ACH DEBIT'), ('CASH', 'CASH'), ('CHECKS', 'CHECKS'), ('UNKNOWN', 'UNKNOWN')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'CREDIT CARD'), ('DEBIT_CARD', 'DEBIT CARD'), ('ACH_DEBIT', 'ACH DEBIT'), ('CASH', 'CASH'), ('CHECKS', 'CHECKS'), ('UNKNOWN', 'UNKNOWN')], max_length=30, null=True),
        ),
    ]
