# Generated by Django 2.0.13 on 2021-05-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20200706_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrentpayment',
            name='linked_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.RentPayment'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='linked_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.RentPayment'),
        ),
        migrations.AlterField(
            model_name='historicalrentpayment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'RENT'), ('deposit', 'DEPOSIT'), ('utility', 'UTILITY'), ('overdue', 'OVERDUE FEE')], default='rent', max_length=30),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'RENT'), ('deposit', 'DEPOSIT'), ('utility', 'UTILITY'), ('overdue', 'OVERDUE FEE')], default='rent', max_length=30),
        ),
    ]
