# Generated by Django 2.0.13 on 2021-05-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20210504_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrentpayment',
            name='linked_reason',
            field=models.CharField(blank=True, choices=[('overdue', 'OVERDUE'), ('FAILED', 'FAILED')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='linked_reason',
            field=models.CharField(blank=True, choices=[('overdue', 'OVERDUE'), ('FAILED', 'FAILED')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrentpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], max_length=30),
        ),
    ]
