
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T17:50:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3fe352cf08aa5137c6331a103b90bb0c84543b2",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
