# Generated by Django 2.0.13 on 2020-07-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_historicalconstruction_historicalconstructionexpense_historicalconstructionpersonnelexpense_historic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionexpense',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='constructionpersonnelexpense',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='historicalconstructionexpense',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='historicalconstructionpersonnelexpense',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterUniqueTogether(
            name='constructionpersonnelexpense',
            unique_together={('construction', 'worker', 'date')},
        ),
    ]
