# Generated by Django 2.0.13 on 2020-09-24 06:43

from django.db import migrations, models

import buildblock.apps.construction.models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_auto_20200924_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionoutsourcingcontract',
            name='attachment',
            field=models.FileField(blank=True, upload_to=buildblock.apps.construction.models.construction_outsourcing_contract_path, verbose_name='Attachment'),
        ),
    ]
