[tool.poetry]
name = "pandas-estat"
version = "0.3.0"
description = "Fetch e-Stat data as Pandas DataFrame."
authors = ["Shota Imaki <shota.imaki.0801@gmail.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/simaki/pandas-estat"

[tool.poetry.dependencies]
python = "^3.6.13"
pandas = "^1.1.4"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
codecov = "^2.1.10"
black = "^21.4b0"
isort = "^5.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
force_single_line = true
