[tool.poetry]
name = "pwcheck"
version = "0.3.1"
description = "Python Password Checker"
authors = ["Itotutona <itotutona.github@evta.fr>"]
license = "GNU"
repository = "https://github.com/Itotutona/pwcheck"
documentation = "https://github.com/Itotutona/pwcheck/tree/master/docs"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
    "setuptools_scm>=3.3.1",
    "poetry-core>=1.0.0"
]
build-backend = "poetry.core.masonry.api"


