# Generated by Django 2.0.13 on 2019-08-14 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20190813_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='owned_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(choices=[('condominium', 'Condominium'), ('townhouse', 'Townhouse'), ('co_op', 'Co-op'), ('single_family ', 'Single Family'), ('land', 'Land'), ('multi_family', 'Multi Family')], max_length=64, verbose_name='Product Property Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('KS', 'Kansas'), ('GA', 'Georgia'), ('DE', 'Delaware'), ('OR', 'Oregon'), ('SC', 'South Carolina'), ('IN', 'Indiana'), ('ND', 'North Dakota'), ('VA', 'Virginia'), ('NE', 'Nebraska'), ('AK', 'Alaska'), ('WY', 'Wyoming'), ('NV', 'Nevada'), ('PA', 'Pennsylvania'), ('HI', 'Hawaii'), ('CT', 'Connecticut'), ('MI', 'Michigan'), ('NC', 'North Carolina'), ('OH', 'Ohio'), ('IA', 'Iowa'), ('WA', 'Washington'), ('SD', 'South Dakota'), ('ME', 'Maine'), ('OK', 'Oklahoma'), ('MN', 'Minnesota'), ('KY', 'Kentucky'), ('CO', 'Colorado'), ('MO', 'Missouri'), ('VT', 'Vermont'), ('AR', 'Arkansas'), ('WV', 'West Virginia'), ('AZ', 'Arizona'), ('ID', 'Idaho'), ('MS', 'Mississippi'), ('MA', 'Massachusetts'), ('MT', 'Montana'), ('WI', 'Wisconsin'), ('NJ', 'New Jersey'), ('FL', 'Florida'), ('NH', 'New Hampshire'), ('TX', 'Texas'), ('CA', 'California'), ('RI', 'Rhode Island'), ('UT', 'Utah'), ('TN', 'Tennessee'), ('DC', 'District of Columbia'), ('AL', 'Alabama'), ('IL', 'Illinois'), ('MD', 'Maryland'), ('NY', 'New York'), ('NM', 'New Mexico'), ('LA', 'Louisiana')], max_length=16, verbose_name='State'),
        ),
    ]
