# Generated by Django 2.0.13 on 2019-08-14 23:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190814_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amenities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='built_year',
            field=models.PositiveIntegerField(default=1967, verbose_name='Building Built'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(choices=[('land', 'Land'), ('multi_family', 'Multi Family'), ('co_op', 'Co-op'), ('condominium', 'Condominium'), ('townhouse', 'Townhouse'), ('single_family ', 'Single Family')], max_length=64, verbose_name='Product Property Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('MA', 'Massachusetts'), ('NV', 'Nevada'), ('MI', 'Michigan'), ('DC', 'District of Columbia'), ('OK', 'Oklahoma'), ('NE', 'Nebraska'), ('SD', 'South Dakota'), ('CO', 'Colorado'), ('KS', 'Kansas'), ('FL', 'Florida'), ('MN', 'Minnesota'), ('AR', 'Arkansas'), ('OH', 'Ohio'), ('OR', 'Oregon'), ('UT', 'Utah'), ('VA', 'Virginia'), ('WY', 'Wyoming'), ('ND', 'North Dakota'), ('TX', 'Texas'), ('NC', 'North Carolina'), ('HI', 'Hawaii'), ('WA', 'Washington'), ('AZ', 'Arizona'), ('RI', 'Rhode Island'), ('WI', 'Wisconsin'), ('IA', 'Iowa'), ('VT', 'Vermont'), ('ME', 'Maine'), ('ID', 'Idaho'), ('NH', 'New Hampshire'), ('WV', 'West Virginia'), ('AK', 'Alaska'), ('IL', 'Illinois'), ('MT', 'Montana'), ('NM', 'New Mexico'), ('GA', 'Georgia'), ('NY', 'New York'), ('MS', 'Mississippi'), ('PA', 'Pennsylvania'), ('CA', 'California'), ('DE', 'Delaware'), ('MD', 'Maryland'), ('SC', 'South Carolina'), ('TN', 'Tennessee'), ('MO', 'Missouri'), ('NJ', 'New Jersey'), ('CT', 'Connecticut'), ('AL', 'Alabama'), ('IN', 'Indiana'), ('KY', 'Kentucky'), ('LA', 'Louisiana')], max_length=16, verbose_name='State'),
        ),
    ]
