# Generated by Django 2.0.13 on 2019-08-15 00:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190814_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amenities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(choices=[('townhouse', 'Townhouse'), ('condominium', 'Condominium'), ('single_family ', 'Single Family'), ('co_op', 'Co-op'), ('multi_family', 'Multi Family'), ('land', 'Land')], max_length=64, verbose_name='Product Property Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('VA', 'Virginia'), ('VT', 'Vermont'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('TX', 'Texas'), ('NY', 'New York'), ('ME', 'Maine'), ('CA', 'California'), ('KY', 'Kentucky'), ('MS', 'Mississippi'), ('WA', 'Washington'), ('MT', 'Montana'), ('MI', 'Michigan'), ('OK', 'Oklahoma'), ('DC', 'District of Columbia'), ('MN', 'Minnesota'), ('SC', 'South Carolina'), ('MO', 'Missouri'), ('NH', 'New Hampshire'), ('GA', 'Georgia'), ('IL', 'Illinois'), ('DE', 'Delaware'), ('LA', 'Louisiana'), ('AZ', 'Arizona'), ('NM', 'New Mexico'), ('CO', 'Colorado'), ('AK', 'Alaska'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('NJ', 'New Jersey'), ('ND', 'North Dakota'), ('AR', 'Arkansas'), ('WI', 'Wisconsin'), ('NC', 'North Carolina'), ('ID', 'Idaho'), ('NV', 'Nevada'), ('NE', 'Nebraska'), ('UT', 'Utah'), ('AL', 'Alabama'), ('IN', 'Indiana'), ('MD', 'Maryland'), ('OH', 'Ohio'), ('RI', 'Rhode Island'), ('MA', 'Massachusetts'), ('SD', 'South Dakota'), ('FL', 'Florida'), ('WY', 'Wyoming'), ('TN', 'Tennessee'), ('WV', 'West Virginia'), ('KS', 'Kansas'), ('CT', 'Connecticut')], max_length=16, verbose_name='State'),
        ),
    ]
