# Generated by Django 2.0.13 on 2019-10-23 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application_fee_rate',
            field=models.FloatField(default=0.05, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Application Fee Rate'),
        ),
    ]
