# Generated by Django 2.0.13 on 2019-11-19 07:52

import buildblock.apps.core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_auto_20191112_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='constructor',
            field=models.ManyToManyField(blank=True, related_name='related_constructions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='zip_code',
            field=buildblock.apps.core.models.ZipcodeField(max_length=5, validators=[django.core.validators.RegexValidator(message='Must be a valid Zipcode in format 12345', regex='^[0-9]{5}$')]),
        ),
    ]
