# Generated by Django 2.0.13 on 2020-01-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
        ('product', '0012_auto_20191119_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='investment_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.InvestmentProduct'),
        ),
    ]
