# Generated by Django 2.0.13 on 2020-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_investment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Construction'), ('ACTIVE', 'Available'), ('PENDING', 'Under Review'), ('INVESTMENT', 'Investment')], default='ACTIVE', max_length=16, verbose_name='Product Status'),
        ),
    ]
