# Generated by Django 2.0.13 on 2020-05-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200427_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionwork',
            old_name='zone',
            new_name='zone_id',
        ),
    ]
