# Generated by Django 2.0.13 on 2020-05-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200513_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionwork',
            old_name='zone_id',
            new_name='zone_ids',
        ),
    ]
