# Generated by Django 2.0.13 on 2021-04-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_group'),
        ('product', '0020_historicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.Group'),
        ),
        migrations.AddField(
            model_name='product',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Group'),
        ),
    ]
