[tool.poetry]
name = "kepler-apertures"
version = "0.1.0"
description = "Tools to compute PRF models from Kepler's FFI and use them to do aperture photometry and compile light curves of the EXBA masks. "
authors = ["Jorge Martinez-Palomera <jorgemarpa@ug.uchile.cl>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jorgemarpa/kepler-apertures"
repository = "https://github.com/jorgemarpa/kepler-apertures"
keywords = ["NASA, Kepler, Astronomy"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
]

[tool.coverage.paths]
source = ["./src"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.4"
astropy = "^4.2"
scipy = "^1.6.1"
matplotlib = "^3.3.4"
photutils = "^1.0.2"
pandas = "1.2.*"
tqdm = "^4.59.0"
patsy = "^0.5.1"
pyia = "^1.2"
lightkurve = "^2.0.4"
wget = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
flake8 = "^3.8.1"
jupyterlab = "^2.2.2"
line-profiler = "^3.0.2"
memory-profiler = "^0.58.0"
black = "^20.8b1"
exoplanet = "^0.4.4"
ipywidgets = "^7.6.3"
mkdocs = "^1.1.2"
mkdocs-material = "^7.0.6"
mkdocstrings = {version = "^0.15.0", extras = ["numpy-style"]}
pytkdocs = {version = "^0.11.0", extras = ["numpy-style"]}
mkdocs-jupyter = "^0.17.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
