# Generated by Django 2.0.13 on 2020-01-09 07:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentcontract',
            old_name='fund',
            new_name='investment',
        ),
        migrations.AlterField(
            model_name='investmentcontract',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
