# Generated by Django 2.0.13 on 2020-02-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_investmentcontract_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='type',
            field=models.CharField(choices=[('ATTACHMENT', 'Attachment'), ('SIGNATURE', 'Signature Contract')], default='ATTACHMENT', max_length=20, verbose_name='Template Type'),
        ),
    ]
