# Generated by Django 2.0.13 on 2020-03-20 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0005_contracttemplate_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentcontract',
            old_name='metadata',
            new_name='records',
        ),
        migrations.AddField(
            model_name='investmentcontract',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='investmentcontract',
            name='status',
            field=models.CharField(choices=[('SIG_REQUIRED_WAITING', 'Waiting for Others'), ('SIG_REQUIRED_PENDING', 'Need to Sign'), ('SIG_REQUIRED_COMPLETE', 'Completed'), ('SIG_NOT_REQUIRED_PENDING', 'Unread'), ('SIG_NOT_REQUIRED_COMPLETE', 'Read')], default='SIG_NOT_REQUIRED_PENDING', max_length=40, verbose_name='Contract Status'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('investment_product', 'user')},
        ),
    ]
