# Generated by Django 2.0.13 on 2020-04-02 08:59

import private_storage.fields
import private_storage.storage.files
from django.db import migrations

import buildblock.apps.investment.models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_auto_20200320_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentcontract',
            name='document_file',
            field=private_storage.fields.PrivateFileField(blank=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=buildblock.apps.investment.models.investment_contract_document_path, verbose_name='Document file'),
        ),
    ]
