# Generated by Django 2.0.13 on 2020-08-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_auto_20200806_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentstep',
            name='actor_role',
            field=models.CharField(choices=[('investor_role', 'Investor'), ('manager_role', 'Manager')], default='manager_role', max_length=100, verbose_name='Actor Role'),
        ),
    ]
