# Generated by Django 2.0.13 on 2020-09-09 01:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0013_contracttemplate_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvestmentstep',
            old_name='stage',
            new_name='stage_id',
        ),
        migrations.RenameField(
            model_name='investmentstep',
            old_name='stage',
            new_name='stage_id',
        ),
        migrations.AlterField(
            model_name='historicalinvestmentstep',
            name='stage_id',
            field=models.CharField(max_length=20, verbose_name='Stage ID'),
        ),
        migrations.AlterField(
            model_name='investmentstep',
            name='stage_id',
            field=models.CharField(max_length=20, verbose_name='Stage ID'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='related_workflow_templates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='historicalinvestmentstep',
            name='step_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Step ID'),
        ),
        migrations.AddField(
            model_name='investmentstep',
            name='step_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Step ID'),
        ),
    ]
