# Generated by Django 2.1.3 on 2019-08-02 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_product', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('WONT_FIX', 'WONT_FIX')], max_length=20, verbose_name='Status'),
        ),
    ]
