# Generated by Django 2.0.13 on 2020-06-11 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_lease_is_auto_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='payment_day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Payment Day'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
