# Generated by Django 2.0.13 on 2021-04-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20210416_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('WONT_FIX', 'WONT_FIX')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
