[tool.poetry]
authors = ["Ken Van Haren <kenvanharen@gmail.com>"]
description = "Functional Data Pipelines"
license = "BSD-3-Clause"
name = "basis-core"
packages = [
  {include = "basis"},
]
version = "0.1.0"

[tool.poetry.dependencies]
alembic = "^1.5.5"
backoff = "^1.10.0"
cleo = "^0.8.1"
click = "^7.1.1"
colorful = "^0.5.4"
common-model = "~0.1.4"
cookiecutter = "^1.7.2"
datacopy = "~0.1.6"
jinja2 = "^3.0.0"
loguru = "^0.5.1"
networkx = "^2.4"
pandas = "^1.0.1"
pyarrow = "^3.0.0"
pydantic = "^1.8.1"
pydantic-sqlalchemy = "^0.0.9"
python = "^3.7.4"
ratelimit = "^2.2.1"
requests = "^2.23.0"
sqlalchemy = "^1.4.1"
sqlparse = "^0.3.1"
strictyaml = "^1.0.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
# common-model = {path = "../common-model/python", develop = true}
# datacopy = {path = "../dcp", develop = true}
Flask = "^2.0.1"
flake8 = "^3.8.1"
ipython = "^7.13.0"
isort = "^4.3.21"
mkdocs = "^1.1.2"
mkdocs-material = "^6.1.7"
mypy = "^0.770"
pre-commit = "^2.1.1"
psycopg2-binary = "^2.8.6"
pydeps = "^1.9.0"
pytest = "^4.6"
pytest-cov = "^2.8.1"
sqlalchemy-stubs = "^0.3"

[tool.poetry.scripts]
basis = "basis.cli:app"

[tool.black]
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | build
  | dist
  | basis/templates/templates
)/
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
skip_glob = "examples/*"
use_parentheses = true

[tool.pytest.ini_options]
addopts = "-ra -q"
norecursedirs = [
  "tests/_test_module/*",
]
testpaths = [
  "tests",
]

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
