[tool.poetry]
name = "acdc"
version = "0.1.0"
description = "Wanna-be fast string search"
authors = ["Amirouche <amirouche@hyper.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
memory-profiler = "^0.58.0"

[tool.poetry.dev-dependencies]
ahocorapy = "^1.6.1"
scalene = "^1.3.8"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
debug = "^0.3.2"
awscli = "^1.19.105"
html2text = "^2020.1.16"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
