
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-03T10:55:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e583f7be6c6e3ed8e814579633d27696477bc1e",
 "version": "0.8.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
