
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T14:32:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "31272f6ad84fed978a697ad9a19468b5707baf5f",
 "version": "21.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
