# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: x86 tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  smoketest-linux:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Build C++ libraries
      run: make
    - name: Smoketest
      run: python -m scalene test/multiprocessing_test.py
  smoketest-macos:

    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # workaround for missing arm64 support: https://github.com/actions/virtual-environments/issues/2557
        sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
        pip install -e .
    - name: Build C++ libraries
      run: make
    - name: Smoketest
      run: python -m scalene test/multiprocessing_test.py

