
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T11:57:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf98c3171e0db10f5b7c37dcb91acb2fee0aed55",
 "version": "1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
