"""
    DataMeta

    DataMeta  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: leon.kuchenbecker@uni-tuebingen.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import datameta_client_lib
from datameta_client_lib.model.error import Error
globals()['Error'] = Error
from datameta_client_lib.model.error_model import ErrorModel


class TestErrorModel(unittest.TestCase):
    """ErrorModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorModel(self):
        """Test ErrorModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
