name: Python package tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        container-name:
          - centos/python-27-centos7
          - centos/python-38-centos7
    container:
      image: ${{ matrix.container-name }}
      options: --user root

    steps:
    - name: Update Git on Container
      run: |
        yum install -y https://repo.ius.io/ius-release-el7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        yum remove -y git
        yum install -y git224

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        rpm -ivh ${{ secrets.FILESERVER_URL }}/centos/7.9.2009/exabyte/x86_64/Packages/torque-6.0.0.1-1.adaptive.el7.centos.x86_64.rpm
        rpm -ivh ${{ secrets.FILESERVER_URL }}/centos/7.9.2009/exabyte/x86_64/Packages/torque-devel-6.0.0.1-1.adaptive.el7.centos.x86_64.rpm
        bash -c 'python -m pip install pip==20.3.4  # Install a version of pip which understands python_requires, to support py 2'
        bash -c 'python -m pip install --upgrade pip'
        bash -c 'python -m pip install --upgrade setuptools wheel'
        bash -c 'pip install -r requirements-dev.txt --no-deps'

    - name: Unit tests
      run: |
        bash -c 'python -m unittest discover --verbose --catch --start-directory tests/unit'
