#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['flitenv']

package_data = \
{'': ['*']}

install_requires = \
['flit', 'dephell-venvs', 'pip-tools', 'toml']

extras_require = \
{'lint': ['flake8', 'isort', 'mypy', 'types-toml'], 'test': ['pytest']}

entry_points = \
{'console_scripts': ['flitenv = flitenv:entrypoint']}

setup(name='flitenv',
      version='0.3.3',
      description='Manage venvs for a flit project',
      author='Gram',
      author_email='gram@orsinium.dev',
      url='https://github.com/orsinium-labs/flitenv',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
