[tool.poetry]
name = "sa11y"
version = "0.0.2"
description = "The Selenium Accessibility Project"
authors = ["Your Name <you@example.com>"]
license = "MPL 2.0"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.4"
flake8 = "^3.9.2"
selenium = "3.141.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
