
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-05T10:35:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "69c89003a22b1efcaedb9a59df9bb08ba9c359bf",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
