
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T12:19:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b0ee415c4061fc9466ee4ed9686c86822db3f56",
 "version": "1.6.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
