
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-28T16:17:11+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "2d0079744716643aed7ed8a9690b27c5e03d594b",
 "version": "0.2.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
