# Generated by Django 2.0.13 on 2021-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('investment', 'Management Service'), ('management', 'Investment Service'), ('construction', 'Construction Service')], max_length=100, verbose_name='Service Type')),
                ('agreement_type', models.CharField(choices=[('tos', 'Terms of Service'), ('pp', 'Privacy Policy'), ('pay', 'Payment Policy')], max_length=100, verbose_name='Agreements Type')),
                ('language', models.CharField(choices=[('en', 'English'), ('ko', 'Korean')], max_length=10, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('num', models.PositiveIntegerField(default=1, verbose_name='Number')),
                ('language', models.CharField(choices=[('en', 'English'), ('ko', 'Korean')], max_length=10)),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
