
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-11T17:40:53+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "9e466220883c22d2071dccde0453697bc40a7a9d",
 "version": "9.1.1.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
