UNIT_MULTIPLIER = 100
MAX_EPOCH = 9999999999

BANK = 'BANK'
VIRTUAL = 'VIRTUAL'

ETH = 'ETH'
BBT = 'BBT'
PJT = 'PJT'
KRW = 'KRW'
USD = 'USD'

PROCESSING = 'PROCESSING'
WAITING = 'WAITING'
COMPLETE = 'COMPLETE'
RETURNED = 'RETURNED'

PAYIN = 'PAYIN'
PAYOUT = 'PAYOUT'
INTEREST = 'INTEREST'
RESALE = 'RESALE'

CHARGE = 'CHARGE'
RETURN_INVESTMENT = 'RETURN_INVESTMENT'
MANUAL = 'MANUAL'
