---
image: python:3.7-buster
jobs:
  script:
    - MY_IP=$(ip r show default | cut -f3 -d' ') tests/setup.sh
    - pip install tox
    - MY_IP=$(ip r show default | cut -f3 -d' ') tox

  after_script:
    - tests/setup.sh teardown
