
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-27T16:32:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "67c68a41fad85bc9c0b1f6bdae197ca83cb81c6a",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
