# Generated by Django 2.0.13 on 2020-01-09 05:55

import datetime

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('survey_amount', models.CharField(choices=[('less_than_100000', 'less than $100,000'), ('100000_500000', '$100,000~$500,000'), ('500000_1M', '$500,000~$1M'), ('more_than_1M', 'more than $1M'), ('undecided', 'undecided')], max_length=100, verbose_name='Survey Amount')),
                ('survey_purpose', models.CharField(choices=[('long-term', 'long-term investment'), ('short-term', 'short-term investment'), ('migration', 'investment migration'), ('undecided', 'undecided')], max_length=100, verbose_name='Survey Purpose')),
                ('message', models.TextField(verbose_name='Question')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('news_category', models.CharField(choices=[('NEWS', 'News'), ('BLOG', 'Blog'), ('NOTICE', 'Notice'), ('EVENT', 'Event'), ('INTERVIEW', 'Interview')], max_length=20, verbose_name='Category')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=30000, verbose_name='Content')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='landing/news', verbose_name='Thumbnail')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Update Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
