# Generated by Django 2.0.13 on 2020-03-26 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_news_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='headline',
            field=models.BooleanField(default=False, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='news',
            name='report_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Report Date'),
        ),
    ]
