# Generated by Django 2.0.13 on 2020-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20200326_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('NEWS', 'News'), ('BLOG', 'Blog'), ('NOTICE', 'Notice'), ('EVENT', 'Event'), ('INTERVIEW', 'Interview'), ('CAREER', 'Career')], max_length=20, verbose_name='Category'),
        ),
    ]
