# Generated by Django 2.0.13 on 2020-10-26 09:00

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20201008_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Video Url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='historicalcasestudy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='casestudyvideo',
            name='case_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='landing.CaseStudy'),
        ),
    ]
