# ┌────────────────────────────────────────────────────────────────────────────────────┐
# │ GENERAL CONSTANTS                                                                  │
# └────────────────────────────────────────────────────────────────────────────────────┘

API = "api"
CHUNK = "chunk"
CODE = "code"
EXCHANGE_READ = "exchange_read"
FEE_BUY = "fee_buy"
FEE_SELL = "fee_sell"
FREQUENCY = "frequency"
GAP = "gap"
IS_ACTIVE = "is_active"
LABEL = "label"
LIMIT = "limit"
MAKER = "maker"
MONGO_READ = "mongo_read"
MONGO_WRITE = "mongo_write"
NULL = "null"
ORDER_KIND_BUY = "order_kind_buy"
ORDER_KIND_SELL = "order_kind_sell"
PRECISION = "precision"
PRECISION_AMOUNT = "precision_amount"
PRECISION_DISPLAY = "precision_display"
PRECISION_PRICE = "precision_price"
PRICE = "price"
PRICE_ASK = "price_ask"
PRICE_BID = "price_bid"
PRICE_MEAN = "price_mean"
SECRET = "secret"
STAKE_AMOUNT_BASE = "stake_amount_base"
STAKE_AMOUNT_CURRENCY_CODE_BASE = "stake_amount_currency_code_base"
STAKE_AMOUNT_CURRENCY_CODE_QUOTE = "stake_amount_currency_code_quote"
STAKE_AMOUNT_MIN_BASE = "stake_amount_min_base"
STAKE_AMOUNT_MIN_CURRENCY_CODE_BASE = "stake_amount_min_currency_code_base"
STAKE_AMOUNT_MIN_CURRENCY_CODE_QUOTE = "stake_amount_min_currency_code_quote"
STAKE_AMOUNT_MIN_QUOTE = "stake_amount_min_quote"
STAKE_AMOUNT_QUOTE = "stake_amount_quote"
SYMBOL_USDT = "USDT"
TAKER = "taker"
TIMEOUT = "timeout"
TIMESTAMP = "timestamp"
TOTAL = "total"
TYPE = "type"
VALIDATOR = "validator"
VOLUME = "volume"
VOLUME_ASK = "volume_ask"
VOLUME_BID = "volume_bid"
VOLUME_MEAN = "volume_mean"
VOLUME_TOTAL = "volume_total"

# ┌────────────────────────────────────────────────────────────────────────────────────┐
# │ TIMEFRAME CONSTANTS                                                                │
# └────────────────────────────────────────────────────────────────────────────────────┘

TF1m = "1m"
TF3m = "3m"
TF5m = "5m"
TF15m = "15m"
TF30m = "30m"
TF1h = "1h"
TF2h = "2h"
TF4h = "4h"
TF6h = "6h"
TF8h = "8h"
TF12h = "12h"
TF1d = "1d"
TF3d = "3d"
TF7d = "1w"
TF1M = "1M"

# ┌────────────────────────────────────────────────────────────────────────────────────┐
# │ FREQUENCY CONSTANTS                                                                │
# └────────────────────────────────────────────────────────────────────────────────────┘

F1m = "1min"
F3m = "3min"
F5m = "5min"
F15m = "15min"
F30m = "30min"
F1h = "1H"
F2h = "2H"
F4h = "4H"
F6h = "6H"
F8h = "8H"
F12h = "12H"
F1d = "1D"
F3d = "3D"
F7d = "7D"
F28d = "28D"
F1M = "1M"
F1Y = "1Y"
