# Generated by Django 2.0.13 on 2019-08-08 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190806_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='account_bank',
            field=models.CharField(max_length=128, verbose_name='Account Bank'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='account_number',
            field=models.CharField(max_length=128, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='address_1',
            field=models.CharField(max_length=128, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='state',
            field=models.CharField(choices=[('MD', 'Maryland'), ('WV', 'West Virginia'), ('AZ', 'Arizona'), ('DE', 'Delaware'), ('SC', 'South Carolina'), ('GA', 'Georgia'), ('MI', 'Michigan'), ('HI', 'Hawaii'), ('CA', 'California'), ('TX', 'Texas'), ('WA', 'Washington'), ('WY', 'Wyoming'), ('MS', 'Mississippi'), ('NM', 'New Mexico'), ('ND', 'North Dakota'), ('ME', 'Maine'), ('KY', 'Kentucky'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('CT', 'Connecticut'), ('AK', 'Alaska'), ('OH', 'Ohio'), ('SD', 'South Dakota'), ('OK', 'Oklahoma'), ('RI', 'Rhode Island'), ('UT', 'Utah'), ('WI', 'Wisconsin'), ('ID', 'Idaho'), ('MA', 'Massachusetts'), ('OR', 'Oregon'), ('TN', 'Tennessee'), ('IN', 'Indiana'), ('VA', 'Virginia'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('FL', 'Florida'), ('KS', 'Kansas'), ('DC', 'District of Columbia'), ('MN', 'Minnesota'), ('LA', 'Louisiana'), ('AR', 'Arkansas'), ('NY', 'New York'), ('AL', 'Alabama'), ('NE', 'Nebraska'), ('PA', 'Pennsylvania'), ('VT', 'Vermont'), ('NV', 'Nevada'), ('CO', 'Colorado'), ('IA', 'Iowa'), ('IL', 'Illinois')], max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Must be valid Zipcode in formats 12345 or 12345-1234', regex='^(^[0-9]{5}(?:-[0-9]{4})?$|^$)')], verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='profiletenant',
            name='credit_score',
            field=models.CharField(default=0, max_length=10, verbose_name='Cedit Score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiletenant',
            name='emergency_contact',
            field=models.CharField(default=0, max_length=300, verbose_name='Emergency Contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiletenant',
            name='income',
            field=models.PositiveIntegerField(default=0, verbose_name='Income'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiletenant',
            name='occupation',
            field=models.CharField(default=None, max_length=300, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(choices=[('KR', '한국'), ('US', '미국'), ('VIE', '베트남'), ('ETC', '그 외')], max_length=15, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter only numbers. Up to 15 digits allowed.', regex='^\\d{9,15}$')], verbose_name='Phone Number'),
        ),
    ]
