# Generated by Django 2.0.13 on 2019-08-08 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190808_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='state',
            field=models.CharField(choices=[('ID', 'Idaho'), ('CT', 'Connecticut'), ('SD', 'South Dakota'), ('GA', 'Georgia'), ('MI', 'Michigan'), ('TN', 'Tennessee'), ('MA', 'Massachusetts'), ('WA', 'Washington'), ('HI', 'Hawaii'), ('CO', 'Colorado'), ('NJ', 'New Jersey'), ('NC', 'North Carolina'), ('NH', 'New Hampshire'), ('WV', 'West Virginia'), ('MO', 'Missouri'), ('OR', 'Oregon'), ('DC', 'District of Columbia'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('IA', 'Iowa'), ('LA', 'Louisiana'), ('MS', 'Mississippi'), ('NY', 'New York'), ('ND', 'North Dakota'), ('NM', 'New Mexico'), ('UT', 'Utah'), ('RI', 'Rhode Island'), ('MT', 'Montana'), ('WY', 'Wyoming'), ('ME', 'Maine'), ('AR', 'Arkansas'), ('NE', 'Nebraska'), ('MD', 'Maryland'), ('TX', 'Texas'), ('VT', 'Vermont'), ('NV', 'Nevada'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('PA', 'Pennsylvania'), ('WI', 'Wisconsin'), ('SC', 'South Carolina'), ('IN', 'Indiana'), ('IL', 'Illinois'), ('KS', 'Kansas'), ('AL', 'Alabama'), ('VA', 'Virginia'), ('KY', 'Kentucky'), ('FL', 'Florida'), ('CA', 'California'), ('DE', 'Delaware'), ('MN', 'Minnesota')], max_length=16, verbose_name='State'),
        ),
    ]
