# Generated by Django 2.0.13 on 2019-08-09 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190808_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='user_role',
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='state',
            field=models.CharField(choices=[('ND', 'North Dakota'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('WV', 'West Virginia'), ('SC', 'South Carolina'), ('NE', 'Nebraska'), ('ME', 'Maine'), ('OR', 'Oregon'), ('AR', 'Arkansas'), ('TX', 'Texas'), ('WA', 'Washington'), ('UT', 'Utah'), ('ID', 'Idaho'), ('NM', 'New Mexico'), ('MO', 'Missouri'), ('IN', 'Indiana'), ('OK', 'Oklahoma'), ('AZ', 'Arizona'), ('CO', 'Colorado'), ('GA', 'Georgia'), ('OH', 'Ohio'), ('MI', 'Michigan'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('TN', 'Tennessee'), ('FL', 'Florida'), ('NV', 'Nevada'), ('DE', 'Delaware'), ('SD', 'South Dakota'), ('HI', 'Hawaii'), ('PA', 'Pennsylvania'), ('MA', 'Massachusetts'), ('NY', 'New York'), ('VT', 'Vermont'), ('AK', 'Alaska'), ('AL', 'Alabama'), ('DC', 'District of Columbia'), ('CA', 'California'), ('MT', 'Montana'), ('WI', 'Wisconsin'), ('NC', 'North Carolina'), ('CT', 'Connecticut'), ('IL', 'Illinois'), ('MN', 'Minnesota'), ('VA', 'Virginia'), ('MD', 'Maryland'), ('NJ', 'New Jersey'), ('WY', 'Wyoming'), ('MS', 'Mississippi'), ('NH', 'New Hampshire'), ('RI', 'Rhode Island')], max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Must be valid Zipcode in format 12345', regex='^[0-9]{5}$')], verbose_name='Zip Code'),
        ),
    ]
