# Generated by Django 2.0.13 on 2019-09-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190815_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletenant',
            name='ssn',
            field=models.CharField(default='NOT_SET', max_length=20, verbose_name='SSN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiletenant',
            name='credit_score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedit Score'),
        ),
    ]
