# Generated by Django 2.0.13 on 2019-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190915_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletenant',
            name='ssn',
            field=models.CharField(max_length=1500, verbose_name='SSN'),
        ),
    ]
