# Generated by Django 2.0.13 on 2019-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190916_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletenant',
            name='ssn_last4_hashed',
            field=models.CharField(default='NOT_SET', max_length=100, verbose_name='SSN last 4 hashed'),
            preserve_default=False,
        ),
    ]
