# Generated by Django 2.0.13 on 2019-09-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profiletenant_ssn_last4_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletenant',
            name='credit_score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Credit Score'),
        ),
        migrations.AlterField(
            model_name='profiletenant',
            name='ssn',
            field=models.CharField(max_length=1500, verbose_name='SSN'),
        ),
    ]
