# Generated by Django 2.0.13 on 2019-11-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profileowner_stripe_dashboard_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileowner',
            name='stripe_dashboard_url',
        ),
    ]
