# Generated by Django 2.0.13 on 2019-11-19 07:52

import buildblock.apps.core.models
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_profileowner_stripe_dashboard_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=300, verbose_name='Contact')),
                ('address_1', models.CharField(max_length=128, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name='Address 2')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=16, verbose_name='State')),
                ('zip_code', buildblock.apps.core.models.ZipcodeField(max_length=5, validators=[django.core.validators.RegexValidator(message='Must be a valid Zipcode in format 12345', regex='^[0-9]{5}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='zip_code',
            field=buildblock.apps.core.models.ZipcodeField(max_length=5, validators=[django.core.validators.RegexValidator(message='Must be a valid Zipcode in format 12345', regex='^[0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('owner_role', 'Owner'), ('tenant_role', 'Tenant'), ('investor_role', 'Investor'), ('constructor_role', 'Constructor')], max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='profileconstructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_constructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
