# Generated by Django 2.0.13 on 2019-11-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191119_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Stripe Customer Id'),
        ),
    ]
