# Generated by Django 2.0.13 on 2021-04-07 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210407_1446'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0028_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('manager', 'Manager'), ('agency', 'Agency')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='auth.Group'),
        ),
    ]
