[tool.poetry]
name = "codemos"
version = "0.1.2"
description = ""
authors = ["Nathanaël <roipoussiere@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.65.2"
Jinja2 = "^3.0.1"
requests = "^2.25.1"
appdirs = "^1.4.4"
uvicorn = "^0.14.0"
python-dotenv = "^0.18.0"
aiofiles = "^0.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
codemos = 'codemos.main:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

include = ['templates']
