
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T04:39:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4ce1b109d455771f2b38e39b377eb73acf40570",
 "version": "2.5.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
