
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-28T13:06:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "44cbdfd1bdc54a2c4f48df9563217c6b4081d88b",
 "version": "1.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
