
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-02T13:50:25+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9bdd610f97aa832dd879796aa6b9bfe11fa0f07",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
