[tool.poetry]
name = "buildblock"
version = "2.0.0"
description = "Initialize poetry"
authors = ["coloryourlife <95chris0319@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
django = "^3.2.4"
django-redis = "^4.1.0"
django-environ = "^0.4.5"
django-model-utils = "^4.1.1"
django-allauth = "^0.44.0"
django-crispy-forms = "^1.12.0"
django-widget-tweaks = "^1.4.8"
django-ckeditor = "^6.1.0"
django-cors-headers = "^3.7.0"
djangorestframework = "^3.12.4"
coreapi = "^2.3.3"
django-mathfilters = "^1.0.0"
django-private-storage = "^2.3.0"
aws-encryption-sdk = "^3.0.0"
blockscore = "^4.1.0"
paypal-checkout-serversdk = "^1.0.1"
web3 = "^5.20.1"
stripe = "^2.58.0"
langdetect = "^1.0.9"
easy-thumbnails = "^2.7.1"
django-hitcount = "^1.3.3"
docusign-esign = "^3.10.0"
marshmallow = "^3.12.1"
django-simple-history = "^3.0.0"
django-modeltranslation = "^0.17.3"
django-better-admin-arrayfield = "^1.4.2"
googlemaps = "^4.4.5"
django-guardian = "^2.4.0"
us = "^2.0.2"
psycopg2-binary = "^2.9.1"
django-background-tasks = "^1.2.5"
boto3 = "^1.17.104"
argon2-cffi = "^20.1.0"
python-slugify = "^5.0.2"
redis = "^3.5.3"
Pillow = "^8.3.0"
psycopg2 = "^2.9.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
ipdb = "^0.13.9"
Werkzeug = "^2.0.1"
Sphinx = "^4.0.2"
pytest-django = "^4.4.0"
factory-boy = "^3.2.0"
flake8 = "^3.9.2"
coverage = "^5.5"
pre-commit = "^2.13.0"
django-debug-toolbar = "^3.2.1"
django-extensions = "^3.1.3"
django-coverage-plugin = "^2.0.0"
django-storages = "^1.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
