
version: 2

build:
  image: stable

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
   version: 3.7
   install:
     - method: pip
       path: .
       extra_requirements:
         - snowmobile
         - docs
   system_packages: false
