
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-04T17:50:42-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "ae2cd605df0be83d525637cdac888e2c32b87a6c",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
