[tool.poetry]
name = "finstar"
version = "0.2.0"
description = "Modeling financial time series. WIP!"
authors = ["Alexander Junge <alexander.junge@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/JungeAlexander/finstar"
repository = "https://github.com/JungeAlexander/finstar/tree/main/src"
readme = "README.md"
packages = [
    { include = "finstar", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.9"
yfinance = "^0.1.59"
altair = "^4.1.0"
pandas = "^1.2.4"
numpy = "^1.20.3"
pyarrow = "^4.0.1"
pandas-market-calendars = "^2.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.0.16"
pytest = "^6.2.4"
black = "^21.6b0"
pre-commit = "^2.13.0"
mkdocs-material = "^7.1.8"
mkdocs = "^1.2.1"
dvc = {extras = ["s3"], version = "^2.3.0"}
mlflow = "^1.18.0"
bump2version = "^1.0.1"
tox = "^3.23.1"
bandit = "^1.7.0"
tox-gh-actions = "^2.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
