[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "stepwise_mol_bio"
author = "Kale Kundert"
author-email = "kale@thekunderts.net"
home-page = 'https://github.com/kalekundert/stepwise_mol_bio'
description-file = 'README.rst'
requires-python = "~=3.8"
requires = [
  'appcli',
  'appdirs',
  'autoprop',
  'biopython',
  'freezerbox',
  'inform~=1.21',
  'more_itertools~=8.6',
  'numpy',
  'requests',
  'rtoml',
  'stepwise',
  'tidyexc',
]
classifiers = [
  'Programming Language :: Python :: 3',
  'License :: OSI Approved :: MIT License',
]

[tool.flit.metadata.requires-extra]
test = [
  'pytest',
  'pytest-cov',
  'parametrize_from_file',
  'requests_testing',
  're_assert',
  'coveralls',
]
doc = [
  'sphinx',
  'sphinx_rtd_theme',
  'autoclasstoc',
]

[tool.flit.metadata.urls]
'Documentation' = 'https://stepwise_mol_bio.readthedocs.io/en/latest/'
'Version Control' = 'https://github.com/kalekundert/stepwise_mol_bio'
'Bug Tracker' = 'https://github.com/kalekundert/stepwise_mol_bio/issues'
'Continuous Integration' = 'https://github.com/kalekundert/stepwise_mol_bio/actions'
'Test Coverage' = 'https://coveralls.io/github/kalekundert/stepwise_mol_bio'

[tool.flit.entrypoints."stepwise.protocols"]
molbio = "stepwise_mol_bio:Plugin"

[tool.flit.entrypoints."freezerbox.make"]
digest = "stepwise_mol_bio:RestrictionDigest"
gibson = "stepwise_mol_bio:Gibson"
golden-gate = "stepwise_mol_bio:GoldenGate"
inverse-pcr = "stepwise_mol_bio:InversePcr"
ivt = "stepwise_mol_bio:Ivt"
ligate = "stepwise_mol_bio:Ligate"
pcr = "stepwise_mol_bio:Pcr"

aliquot = "stepwise_mol_bio:Aliquot"
lyophilize = "stepwise_mol_bio:Lyophilize"
miniprep = "stepwise_mol_bio:Miniprep"
page-purify = "stepwise_mol_bio:PagePurify"
spin-cleanup = "stepwise_mol_bio:SpinCleanup"

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-glob='*.rst'"
doctest_optionflags = 'NORMALIZE_WHITESPACE'
markers = """slow: marks tests as slow (deselect with '-m "not slow"')"""

[tool.pccc]
header_length = 72
types = ["chore", "docs", "feat", "fix", "refactor", "style", "test"]
scopes = [
  "aliquot",
  "anneal",
  "digest",
  "direct_dilution",
  "ethanol_precipitation",
  "gel",
  "gibson",
  "golden_gate",
  "invpcr",
  "ivt",
  "ivtt",
  "kld",
  "laser_scanner",
  "ligate",
  "lyophilize",
  "miniprep",
  "page_purify",
  "pcr",
  "phenol_chloroform",
  "qpcr",
  "retransform",
  "rnasezap",
  "serial_dilution",
  "spin_cleanup",
  "stain",
  "transform",
  "uv_transilluminator",
]
ignore_generated_commits = true
generated_commits = ['^Merge']

[tool.semantic_release]
version_variable = 'stepwise_mol_bio/__init__.py:__version__'
build_command = 'python -m pip install flit && flit build'
