# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 6, 0):
    raise RuntimeError("Python 3.6 or later required")


from . import _IsotropicWaveletsPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkFrequencyFunctionPython
else:
    import _itkFrequencyFunctionPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _itkFrequencyFunctionPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _itkFrequencyFunctionPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import collections.abc
import itk.itkSpatialFunctionPython
import itk.ITKCommonBasePython
import itk.pyBasePython
import itk.itkPointPython
import itk.vnl_vectorPython
import itk.stdcomplexPython
import itk.vnl_matrixPython
import itk.itkFixedArrayPython
import itk.vnl_vector_refPython
import itk.itkVectorPython
import itk.itkFunctionBasePython
import itk.itkContinuousIndexPython
import itk.itkIndexPython
import itk.itkSizePython
import itk.itkOffsetPython
import itk.itkArrayPython
import itk.itkRGBPixelPython
import itk.itkImagePython
import itk.itkImageRegionPython
import itk.itkCovariantVectorPython
import itk.itkRGBAPixelPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkMatrixPython
import itk.vnl_matrix_fixedPython
class itkFrequencyFunctionD2PD2(itk.itkSpatialFunctionPython.itkSpatialFunctionD2PD2):
    r"""Proxy of C++ itkFrequencyFunctionD2PD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    RadPerSecToHertz = _swig_new_instance_method(_itkFrequencyFunctionPython.itkFrequencyFunctionD2PD2_RadPerSecToHertz)
    __swig_destroy__ = _itkFrequencyFunctionPython.delete_itkFrequencyFunctionD2PD2
    cast = _swig_new_static_method(_itkFrequencyFunctionPython.itkFrequencyFunctionD2PD2_cast)

# Register itkFrequencyFunctionD2PD2 in _itkFrequencyFunctionPython:
_itkFrequencyFunctionPython.itkFrequencyFunctionD2PD2_swigregister(itkFrequencyFunctionD2PD2)
itkFrequencyFunctionD2PD2_cast = _itkFrequencyFunctionPython.itkFrequencyFunctionD2PD2_cast

class itkFrequencyFunctionD3PD3(itk.itkSpatialFunctionPython.itkSpatialFunctionD3PD3):
    r"""Proxy of C++ itkFrequencyFunctionD3PD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    RadPerSecToHertz = _swig_new_instance_method(_itkFrequencyFunctionPython.itkFrequencyFunctionD3PD3_RadPerSecToHertz)
    __swig_destroy__ = _itkFrequencyFunctionPython.delete_itkFrequencyFunctionD3PD3
    cast = _swig_new_static_method(_itkFrequencyFunctionPython.itkFrequencyFunctionD3PD3_cast)

# Register itkFrequencyFunctionD3PD3 in _itkFrequencyFunctionPython:
_itkFrequencyFunctionPython.itkFrequencyFunctionD3PD3_swigregister(itkFrequencyFunctionD3PD3)
itkFrequencyFunctionD3PD3_cast = _itkFrequencyFunctionPython.itkFrequencyFunctionD3PD3_cast

class itkFrequencyFunctionD4PD4(itk.itkSpatialFunctionPython.itkSpatialFunctionD4PD4):
    r"""Proxy of C++ itkFrequencyFunctionD4PD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    RadPerSecToHertz = _swig_new_instance_method(_itkFrequencyFunctionPython.itkFrequencyFunctionD4PD4_RadPerSecToHertz)
    __swig_destroy__ = _itkFrequencyFunctionPython.delete_itkFrequencyFunctionD4PD4
    cast = _swig_new_static_method(_itkFrequencyFunctionPython.itkFrequencyFunctionD4PD4_cast)

# Register itkFrequencyFunctionD4PD4 in _itkFrequencyFunctionPython:
_itkFrequencyFunctionPython.itkFrequencyFunctionD4PD4_swigregister(itkFrequencyFunctionD4PD4)
itkFrequencyFunctionD4PD4_cast = _itkFrequencyFunctionPython.itkFrequencyFunctionD4PD4_cast

class itkFrequencyFunctionF2PD2(itk.itkSpatialFunctionPython.itkSpatialFunctionF2PD2):
    r"""Proxy of C++ itkFrequencyFunctionF2PD2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    RadPerSecToHertz = _swig_new_instance_method(_itkFrequencyFunctionPython.itkFrequencyFunctionF2PD2_RadPerSecToHertz)
    __swig_destroy__ = _itkFrequencyFunctionPython.delete_itkFrequencyFunctionF2PD2
    cast = _swig_new_static_method(_itkFrequencyFunctionPython.itkFrequencyFunctionF2PD2_cast)

# Register itkFrequencyFunctionF2PD2 in _itkFrequencyFunctionPython:
_itkFrequencyFunctionPython.itkFrequencyFunctionF2PD2_swigregister(itkFrequencyFunctionF2PD2)
itkFrequencyFunctionF2PD2_cast = _itkFrequencyFunctionPython.itkFrequencyFunctionF2PD2_cast

class itkFrequencyFunctionF3PD3(itk.itkSpatialFunctionPython.itkSpatialFunctionF3PD3):
    r"""Proxy of C++ itkFrequencyFunctionF3PD3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    RadPerSecToHertz = _swig_new_instance_method(_itkFrequencyFunctionPython.itkFrequencyFunctionF3PD3_RadPerSecToHertz)
    __swig_destroy__ = _itkFrequencyFunctionPython.delete_itkFrequencyFunctionF3PD3
    cast = _swig_new_static_method(_itkFrequencyFunctionPython.itkFrequencyFunctionF3PD3_cast)

# Register itkFrequencyFunctionF3PD3 in _itkFrequencyFunctionPython:
_itkFrequencyFunctionPython.itkFrequencyFunctionF3PD3_swigregister(itkFrequencyFunctionF3PD3)
itkFrequencyFunctionF3PD3_cast = _itkFrequencyFunctionPython.itkFrequencyFunctionF3PD3_cast

class itkFrequencyFunctionF4PD4(itk.itkSpatialFunctionPython.itkSpatialFunctionF4PD4):
    r"""Proxy of C++ itkFrequencyFunctionF4PD4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    RadPerSecToHertz = _swig_new_instance_method(_itkFrequencyFunctionPython.itkFrequencyFunctionF4PD4_RadPerSecToHertz)
    __swig_destroy__ = _itkFrequencyFunctionPython.delete_itkFrequencyFunctionF4PD4
    cast = _swig_new_static_method(_itkFrequencyFunctionPython.itkFrequencyFunctionF4PD4_cast)

# Register itkFrequencyFunctionF4PD4 in _itkFrequencyFunctionPython:
_itkFrequencyFunctionPython.itkFrequencyFunctionF4PD4_swigregister(itkFrequencyFunctionF4PD4)
itkFrequencyFunctionF4PD4_cast = _itkFrequencyFunctionPython.itkFrequencyFunctionF4PD4_cast



