[tool.poetry]
name = "docs_translate"
version = "0.1.6"
description = "CLI tool to translate markdown and reStructuredText files"
authors = ["kyeongin kim <kikim@gmail.com>"]
license = "MIT License"
readme = "README.md"
repository = "https://github.com/gs-kikim/docs-trans-app"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Documentation",
    "Topic :: Utilities",
    "Typing :: Typed"
]

[tool.poetry.scripts]
docs-translate = 'docs_translate.app:run'

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.24.0"
translators = "^4.7.2"
langdetect = "^1.0.8"
loguru = "^0.5.3"
google-cloud-translate = "^2.0.1"


[tool.poetry.dev-dependencies]
coverage = "^5.2"
mypy = "^0.782"
black = "^19.10b0"
isort = "^5.6.4"
pytest = "^6.1.1"
pytest-cov = "^2.10.1"

[tool.black]
exclude = """
(
    tests
)
"""

# Coverage section

[tool.coverage.run]
source = [
    'docs_translate',
]
omit = [
    'tests/*',
    'docs_translate/app.py'
]

[tool.coverage.html]
directory = '.coverage_html'

[tool.coverage.report]
fail_under = 80

exclude_lines = [
    '# pragma: no cover',
    'raise NotImplementedError()',
    'if TYPE_CHECKING:'
]
[tool.isort]
profile = "black"
src_paths = ["docs_translate"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# Black section

