
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T16:38:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e101fb3f84347df713f8812d3796c2c95749997",
 "version": "v0.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
