[tool.poetry]
name = "dnsimple-python"
version = "0.1.0"
description = ""
authors = ["DXTimer <ibbakalov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
attrs="21.2.0"
certifi="2021.5.30"
chardet="4.0.0"
coverage="5.5"
dataclasses-json="0.5.4"
idna="3.2"
marshmallow="3.12.1"
marshmallow-enum="1.5.1"
more-itertools="8.8.0"
mypy-extensions="0.4.3"
omitempty="0.1.1"
packaging="20.9"
pluggy="0.13.1"
py="1.10.0"
pyparsing="2.4.7"
pytest="6.2.4"
requests="2.25.1"
responses="0.13.3"
six="1.16.0"
stringcase="1.2.0"
typing-extensions="3.10.0.0"
typing-inspect="0.7.1"
urllib3="1.26.6"
wcwidth="0.2.5"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
