# Generated by Django 2.0.13 on 2020-01-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_contracttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentcontract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.ContractTemplate'),
        ),
    ]
