# Generated by Django 2.0.13 on 2020-08-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_historicalinvestmentstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestmentcontract',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Contract Title'),
        ),
        migrations.AlterField(
            model_name='investmentcontract',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Contract Title'),
        ),
    ]
