# Generated by Django 2.0.13 on 2020-08-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_auto_20200818_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Template Description'),
        ),
    ]
