
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T13:50:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0903a04c7f42f1e6f2a0b5f384d30a5b24640bc",
 "version": "4.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
