[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pytest_anyio"
dist-name = "pytest-anyio"
author = "Thomas Grainger"
author-email = "pytest-anyio@graingert.co.uk"
home-page = "https://github.com/graingert/pytest-anyio"
classifiers = [ "License :: OSI Approved :: MIT License",]
requires = ["anyio", "pytest"]
