# Generated by Django 2.0.13 on 2019-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190802_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE'), ('WONT_FIX', 'WONT_FIX')], max_length=20, verbose_name='Status'),
        ),
    ]
