# Generated by Django 2.0.13 on 2019-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190815_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='deposit',
            field=models.PositiveIntegerField(verbose_name='Deposit'),
        ),
    ]
