# Generated by Django 2.0.13 on 2019-09-06 10:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190829_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=400, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('WONT_FIX', 'WONT_FIX')], max_length=20, verbose_name='Status'),
        ),
    ]
