# Generated by Django 2.0.13 on 2019-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190906_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='payment_day',
            field=models.PositiveIntegerField(default=1, verbose_name='Payment Day'),
        ),
    ]
