# Generated by Django 2.0.13 on 2019-12-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_lease_payment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_auto_paid',
            field=models.BooleanField(default=False, verbose_name='Automatic Payment'),
        ),
    ]
