# Generated by Django 2.0.13 on 2021-04-06 06:15

import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models

import buildblock.apps.management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_historicallease'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Document title')),
                ('document', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=buildblock.apps.management.models.lease_document_path, verbose_name='Document file')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='management.Lease')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
