# Generated by Django 2.0.13 on 2021-04-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20210408_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallease',
            name='room_num',
            field=models.CharField(max_length=200, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='room_num',
            field=models.CharField(max_length=200, verbose_name='Room Number'),
        ),
    ]
