
# This file was generated by a modified 'versioneer.py' from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

def get_versions():
    return {'version': '1.6.14', 'full-revisionid': 'b46842f2e090291b74b02002b0583a849cf11681', 'dirty': False, 'error': None, 'date': '2021-07-04T23:28:07+0200'}
