
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T23:03:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a2ac1e65f8a02e7ea9bc8cc089dd38fb7c66042",
 "version": "5.1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
