[tool.poetry]
name = "python_projet"
version = "0.1.2"
description = "Projet de generation de ville"
authors = ["Samy Belbachir <samy.belbachir@epita.fr>"]
maintainers = ["Maridiyath Bachirou  <maridiyath-folake-odeofe.bachirou@epita.fr>"]

packages = [ { include = "src", format = "sdist" },
             { include = "tests", format = "sdist" },
             { include = "docs", format = "sdist" },
             { include = "requirements.txt"},
             { include = "README.md" },
             { include = "AUTHORS" },
           ]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
Shapely = "^1.7.1"
matplotlib = "^3.4.2"
numpy = "^1.21.0"
voronoi = "^0.2.0"
Geometry = "^0.0.23"
Fiona = "^1.8.20"
scipy = "^1.7.0"
geopandas = "^0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
