"""
    DataMeta

    DataMeta  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: leon.kuchenbecker@uni-tuebingen.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import datameta_client_lib
from datameta_client_lib.model.identifier import Identifier
from datameta_client_lib.model.whoami_response_group import WhoamiResponseGroup
globals()['Identifier'] = Identifier
globals()['WhoamiResponseGroup'] = WhoamiResponseGroup
from datameta_client_lib.model.user_response import UserResponse


class TestUserResponse(unittest.TestCase):
    """UserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserResponse(self):
        """Test UserResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
