"""
    DataMeta

    DataMeta  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: leon.kuchenbecker@uni-tuebingen.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import datameta_client_lib
from datameta_client_lib.model.server_info_response import ServerInfoResponse


class TestServerInfoResponse(unittest.TestCase):
    """ServerInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerInfoResponse(self):
        """Test ServerInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
