
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T12:19:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe5f1c6db7fbce48ee6fb56ddec69f190bf86eaa",
 "version": "2.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
