
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-02T16:02:39-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2009b0fee51a608bb28eb41e214449307486325d",
 "version": "v3.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
