[tool.poetry]
name = "onvif_utilities"
version = "0.2.0"
description = ""
authors = ["MohammadHossein <hos1377@gmail.com>"]
include = [
    { path = "nvif-python/wsdl"}
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

