
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-05T12:58:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0fddbb9df1b771a9133dc3dd5ea92c18b9165df",
 "version": "2021.07.05"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
