
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T15:53:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "79c6c776e2d9e14e87f2b5166f9ab3b521d122a6",
 "version": "0.4.55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
