
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T11:17:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f344494e1555a19706b5fc825977ca669783e11c",
 "version": "0.7.0.post.dev224"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
