[tool.poetry]
name = "pyespremclient"
version = "0.6.594658"
description = "A python module for ESPREM clients"
authors = ["Zafar Iqbal <ultrasine@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
