# Generated by Django 2.2.18 on 2021-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0015_auto_20210525_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
