[tool.poetry]
name = "velogames"
version = "0.1.0"
description = "Small tool for scraping Velogames data"
authors = ["Ossi Rajuvaara <ossi@robocorp.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
beautifulsoup4 = "^4.9.3"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pylint = "^2.8.3"
mypy = "^0.910"
types-requests = "^2.25.0"

[tool.poetry.scripts]
velogames = 'velogames.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
