
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T14:58:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8fe5e2f2502278a07eb1c3aeeb5774bcbfb58a9",
 "version": "0.4.54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
