
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-25T14:44:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a23ecef1e7c20f13717681eaf320e8c15df10e0",
 "version": "2.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
