#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['oliverfarren_python_test_package']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='oliverfarren_python_test_package',
      version='0.1.0',
      description='oliverfarren-python_test_package',
      author='Oliver Farren',
      author_email='oliver.farren@gmail.com',
      url='https://github.com/OliverFarren/oliverfarren-python-test-package',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
     )
