
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T09:37:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a594d1ddd1019d02c23061bc3250f30278c12f14",
 "version": "2500"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
