# Generated by Django 2.0.13 on 2020-12-31 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import buildblock.apps.messaging.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmessagingtemplates',
            name='location',
        ),
        migrations.RemoveField(
            model_name='messagingtemplates',
            name='location',
        ),
        migrations.AddField(
            model_name='historicalmessagingtemplates',
            name='category',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('INVESTMENT', 'Investment'), ('MANAGEMENT', 'Management'), ('MARKETING', 'Marketing'), ('SUPPORT', 'Support'), ('ETC', 'Etc.')], default='ETC', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='historicalmessagingtemplates',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, default=buildblock.apps.messaging.models.get_default_creator, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmessagingtemplates',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='messagingtemplates',
            name='category',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('INVESTMENT', 'Investment'), ('MANAGEMENT', 'Management'), ('MARKETING', 'Marketing'), ('SUPPORT', 'Support'), ('ETC', 'Etc.')], default='ETC', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='messagingtemplates',
            name='creator',
            field=models.ForeignKey(default=buildblock.apps.messaging.models.get_default_creator, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_template_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagingtemplates',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
