# Generated by Django 2.2.16 on 2020-10-15 07:27

from django.db import migrations, models
import djangoldp_polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0012_auto_20201015_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='endDate',
            field=models.DateField(default=djangoldp_polls.models.onMonthLater, verbose_name='End data'),
        ),
    ]
