# Generated by Django 2.2.18 on 2021-05-25 08:22

from django.db import migrations, models
import django.db.models.deletion
import djangoldp_polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0014_auto_20210525_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='djangoldp_circle.Circle'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='endDate',
            field=models.DateField(blank=True, default=djangoldp_polls.models.onMonthLater, null=True, verbose_name='End data'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.URLField(blank=True, default='https://unpkg.com/@startinblox/component-poll@2.1/img/defaultpoll.png', null=True, verbose_name='Illustration'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='longDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='shortDescription',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Options available for a vote'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='chosenOption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userVote', to='djangoldp_polls.PollOption'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='relatedPoll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='djangoldp_polls.Poll'),
        ),
    ]
