# Generated by Django 3.2 on 2021-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0072_auto_20210408_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debug',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
