# Generated by Django 3.1.8 on 2021-04-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0073_alter_debug_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditmodelex',
            name='creator',
        ),
        migrations.DeleteModel(
            name='E_mails',
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
        migrations.DeleteModel(
            name='AuditModelEx',
        ),
    ]
