# Generated by Django 2.0.13 on 2019-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
