# Generated by Django 2.0.13 on 2019-09-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rentpayment_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'CREDIT_CARD'), ('DEBIT_CARD', 'DEBIT_CARD')], max_length=30, null=True),
        ),
    ]
