# Generated by Django 2.0.13 on 2019-09-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190921_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
