# Generated by Django 2.0.13 on 2019-10-14 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_product_plan_image'),
        ('payments', '0007_rentpayment_payment_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('destination_account', models.CharField(blank=True, max_length=32, null=True)),
                ('account_type', models.CharField(choices=[('stripe', 'Stripe')], max_length=32)),
                ('identifier', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('FAILED_NO_DESTINATION_ACCOUNT', 'FAILED_NO_DESTINATION_ACCOUNT'), ('FAILED_OTHER_REASON', 'FAILED_OTHER_REASON')], max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transfer_owner', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transfer_product', to='product.Product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transfer_tenant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
