# Generated by Django 2.0.13 on 2019-10-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymenttransfers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentpayment',
            old_name='event_id',
            new_name='identifier',
        ),
    ]
