# Generated by Django 2.0.13 on 2019-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20191018_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], max_length=30),
        ),
    ]
