# Generated by Django 2.0.13 on 2019-12-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20191124_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransfers',
            name='source_type',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('card', 'Card')], default='card', max_length=30),
            preserve_default=False,
        ),
    ]
