# Generated by Django 2.0.13 on 2020-06-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_paymenttransfers_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransfers',
            name='transfer_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
