
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T19:39:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "afd6055d7d8560b3969da41bacdd168117bee061",
 "version": "0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
