[tool.poetry]
name = "komolibs"
version = "0.1.13"
description = ""
authors = ["Makhosonke Morafo <makhosonke@komokun.org>"]

[tool.poetry.dependencies]
python = "^3.8"
aioredis = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
