#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['template_maker']

package_data = \
{'': ['*'],
 'template_maker': ['configuration/*',
                    'configuration/template/*',
                    'configuration/template/app/*',
                    'configuration/template/lib/*',
                    'configuration/template/lib/app/*',
                    'configuration/template/lib/lib/*',
                    'configuration/template/lib/lib/include/*',
                    'configuration/template/lib/lib/src/*',
                    'configuration/template/lib/test/*',
                    'configuration/template/lib/test/src/*']}

entry_points = \
{'console_scripts': ['template-maker = template_maker.main:main']}

setup(name='template_maker',
      version='0.0.1',
      description='with the help of this script, create CMake supported conan template empty structure.',
      author='Sheik S Shajeen Ahamed',
      author_email='shajeenahmed@gmail.com',
      url='https://github.com/shajeen/template-maker',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
