
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T12:57:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "779ab45817d262d70f680bd0c9e6d8998f14089a",
 "version": "1.5.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
