# Generated by Django 2.0.13 on 2019-08-09 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190809_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileowner',
            name='state',
            field=models.CharField(choices=[('WY', 'Wyoming'), ('SD', 'South Dakota'), ('NM', 'New Mexico'), ('PA', 'Pennsylvania'), ('MS', 'Mississippi'), ('WV', 'West Virginia'), ('MT', 'Montana'), ('IN', 'Indiana'), ('AK', 'Alaska'), ('UT', 'Utah'), ('VA', 'Virginia'), ('MI', 'Michigan'), ('NV', 'Nevada'), ('NY', 'New York'), ('ND', 'North Dakota'), ('SC', 'South Carolina'), ('AR', 'Arkansas'), ('IL', 'Illinois'), ('NJ', 'New Jersey'), ('TN', 'Tennessee'), ('OR', 'Oregon'), ('ID', 'Idaho'), ('AZ', 'Arizona'), ('ME', 'Maine'), ('WI', 'Wisconsin'), ('KY', 'Kentucky'), ('IA', 'Iowa'), ('CT', 'Connecticut'), ('NC', 'North Carolina'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('NE', 'Nebraska'), ('OK', 'Oklahoma'), ('TX', 'Texas'), ('CO', 'Colorado'), ('AL', 'Alabama'), ('HI', 'Hawaii'), ('FL', 'Florida'), ('CA', 'California'), ('VT', 'Vermont'), ('GA', 'Georgia'), ('MN', 'Minnesota'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('OH', 'Ohio'), ('MO', 'Missouri'), ('RI', 'Rhode Island'), ('KS', 'Kansas'), ('MD', 'Maryland'), ('NH', 'New Hampshire'), ('WA', 'Washington')], max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('owner_role', 'Owner'), ('investor_role', 'Investor'), ('tenant_role', 'Tenant')], max_length=200), blank=True, size=None),
        ),
    ]
