# Generated by Django 2.0.13 on 2019-08-12 07:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190810_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileowner',
            name='state',
            field=models.CharField(choices=[('KY', 'Kentucky'), ('RI', 'Rhode Island'), ('FL', 'Florida'), ('MA', 'Massachusetts'), ('CO', 'Colorado'), ('MO', 'Missouri'), ('IN', 'Indiana'), ('ME', 'Maine'), ('UT', 'Utah'), ('GA', 'Georgia'), ('MD', 'Maryland'), ('NY', 'New York'), ('VT', 'Vermont'), ('TN', 'Tennessee'), ('AL', 'Alabama'), ('MI', 'Michigan'), ('KS', 'Kansas'), ('NC', 'North Carolina'), ('HI', 'Hawaii'), ('NV', 'Nevada'), ('DC', 'District of Columbia'), ('ID', 'Idaho'), ('CA', 'California'), ('MN', 'Minnesota'), ('AZ', 'Arizona'), ('SD', 'South Dakota'), ('NH', 'New Hampshire'), ('ND', 'North Dakota'), ('LA', 'Louisiana'), ('NE', 'Nebraska'), ('WV', 'West Virginia'), ('WA', 'Washington'), ('NM', 'New Mexico'), ('OH', 'Ohio'), ('PA', 'Pennsylvania'), ('WY', 'Wyoming'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('AK', 'Alaska'), ('SC', 'South Carolina'), ('IL', 'Illinois'), ('TX', 'Texas'), ('NJ', 'New Jersey'), ('IA', 'Iowa'), ('VA', 'Virginia'), ('OR', 'Oregon'), ('MT', 'Montana'), ('MS', 'Mississippi'), ('AR', 'Arkansas'), ('OK', 'Oklahoma'), ('WI', 'Wisconsin')], max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('tenant_role', 'Tenant'), ('investor_role', 'Investor'), ('owner_role', 'Owner')], max_length=200), blank=True, default=list, size=None),
        ),
    ]
