# Generated by Django 2.0.13 on 2019-10-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190918_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileowner',
            name='stripe_account',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Stripe Account'),
        ),
    ]
