# Generated by Django 2.0.13 on 2019-10-18 01:41

import buildblock.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profileowner_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletenant',
            name='proof_of_income',
            field=models.FileField(blank=True, upload_to=buildblock.apps.users.models.tenant_file_path, verbose_name='Proof of Income (option)'),
        ),
    ]
