# Generated by Django 2.0.13 on 2019-10-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profiletenant_proof_of_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileowner',
            name='account_bank',
        ),
        migrations.RemoveField(
            model_name='profileowner',
            name='account_number',
        ),
    ]
