# Generated by Django 2.0.13 on 2019-10-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191020_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(choices=[('US', '미국'), ('KR', '한국'), ('VIE', '베트남'), ('ETC', '그 외')], max_length=15, verbose_name='Nationality'),
        ),
    ]
