# Generated by Django 2.0.13 on 2019-11-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191029_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileowner',
            name='stripe_dashboard_url',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Stripe Dashboard URL'),
        ),
    ]
