# Generated by Django 2.0.13 on 2019-12-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profiletenant_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletenant',
            name='auto_payment_account_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Auto Payment Bank Account Id'),
        ),
    ]
