# Generated by Django 2.0.13 on 2020-01-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profiletenant_auto_payment_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='초대 회원 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='need_to_change_password',
            field=models.BooleanField(default=False, verbose_name='비밀번호 재설정 필요 여부'),
        ),
    ]
