# Generated by Django 2.0.13 on 2020-08-14 07:35

import django.core.validators
from django.db import migrations, models

import buildblock.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileowner',
            name='address_1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=16, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='profileowner',
            name='zip_code',
            field=buildblock.apps.core.models.ZipcodeField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Must be a valid Zipcode in format 12345', regex='^[0-9]{5}$')]),
        ),
    ]
