# Generated by Django 2.0.13 on 2021-04-27 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210407_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileagent',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='profileagent',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='profileagent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profileagent',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profileagent',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profileagent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Please enter only numbers. Up to 15 digits allowed.', regex='^\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='profileagent',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position'),
        ),
    ]
