# Generated by Django 2.0.13 on 2021-05-04 09:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210427_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemanager',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='profilemanager',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='profilemanager',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profilemanager',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profilemanager',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profilemanager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Please enter only numbers. Up to 15 digits allowed.', regex='^\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='profilemanager',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='profilemanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
