[tool.poetry]
name = "neon_schemas"
version = "0.1.10"
description = "Schemas for Neon Law"
authors = ["neon law <support@neonlaw.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
avro = "^1.10.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.5b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
