# Generated by Django 2.0.13 on 2020-05-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='PENDING', max_length=16, verbose_name='Construction Status'),
        ),
    ]
