# Generated by Django 2.0.13 on 2020-06-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_auto_20200602_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionexpense',
            name='item',
            field=models.CharField(default='item', max_length=200, verbose_name='Item'),
            preserve_default=False,
        ),
    ]
