# Generated by Django 2.0.13 on 2020-06-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_constructionexpense_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionpersonnelexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
