# Generated by Django 2.0.13 on 2020-06-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_constructionpersonnelexpense_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionpersonnelexpense',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='constructionpersonnelexpense',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
    ]
