# Generated by Django 2.0.13 on 2020-09-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_auto_20200915_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalconstructionoutsourcingexpense',
            name='construction_work',
        ),
        migrations.AddField(
            model_name='constructionoutsourcingexpense',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalconstructionoutsourcingexpense',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionoutsourcingexpense',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='historicalconstructionoutsourcingexpense',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Paid Amount'),
        ),
        migrations.RemoveField(
            model_name='constructionoutsourcingexpense',
            name='construction_work',
        ),
        migrations.AlterUniqueTogether(
            name='constructionoutsourcingexpense',
            unique_together={('outsourcing_contract', 'ordering')},
        ),
    ]
