
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-01T22:09:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "18532bf7f1f69579117849b4cbd894cd16449015",
 "version": "0.1.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
