
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-01T23:32:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "037548708a71dafc975d5ac0ee9fd030d3d0e7bb",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
