
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T13:16:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f21614a2874df89e8cbc8b5d184ed212f16e4d8",
 "version": "v0.4.0a.post.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
