
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-05T12:40:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3276dcb625aa7e80b16bcdb37b27f78d378ef8f",
 "version": "0.1.0a19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
