
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-10T13:05:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebffcc55c7d28e279ce101cb79ea1ff4a3d92411",
 "version": "1.7.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
