[tool.poetry]
name = "pton"
version = "0.1.0"
description = ""
authors = ["Emma Rachlin <emma.rachlin@epita.fr>"]
maintainers = ["Maxence Ramos-Pariente <maxence.ramos-pariente@epita.fr>"]
packages = [ { include = "src", format = "sdist" },
             { include = "docs", format = "sdist" },
	     { include = "README.md" },
           ]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
Shapely = "^1.7.1"
numpy = "^1.21.0"
geopandas = "^0.9.0"
scipy = "^1.7.0"
Fiona = "^1.8.20"
matplotlib = "^3.4.2"
voronoi = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
