
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T13:56:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6aa44465a9c8623a8ad12ee065e258f20ce1e5d",
 "version": "0.13.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
