
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T20:15:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a3c445ed21d112f75e945bc477375ed8e146a61",
 "version": "v3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
