[tool.poetry]
name = "django-pycharm"
version = "0.1.3"
description = "App for Django to run any Python script within Django context"
authors = ["nouseforacode <10090277+nouseforacode@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/nouseforacode/django-pycharm"
repository = "https://github.com/nouseforacode/django-pycharm"


[tool.poetry.dependencies]
python = ">=3.7"
Django = ">=3"
xmltodict = ">=0.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
