
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-30T15:16:19-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a3dabae3ae80c88b635ac744cef10f4c60c68e4",
 "version": "2.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
