
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-25T11:26:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "73497a080b0f1c940b0221910569bd2b0844687a",
 "version": "21.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
