# Generated by Django 2.2.16 on 2020-10-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0011_auto_20200923_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='hostingOrganisation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of the hosting organisation'),
        ),
    ]
