# Generated by Django 2.2.22 on 2021-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0016_vote_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='authorNotificationOnComment',
            field=models.BooleanField(default=True),
        ),
    ]
