- name: Create replicated storage directory
  file:
    path: /srv/shakenfist/replicated
    state: directory
    mode: "0755"

- name: Mount glusterfs to /srv/shakenfist/replicated
  mount:
    path: /srv/shakenfist/replicated
    src: localhost:/shakenfist
    fstype: glusterfs
    state: mounted

- name: Create instance storage directory
  file:
    path: /srv/shakenfist/replicated/instances
    state: directory
    mode: "0755"

- name: Link to instance storage directory
  file:
    src: /srv/shakenfist/replicated/instances
    dest: /srv/shakenfist/instances
    state: link

- name: Create image storage directory
  file:
    path: /srv/shakenfist/replicated/image_cache
    state: directory
    mode: "0755"

- name: Link to image storage directory
  file:
    src: /srv/shakenfist/replicated/image_cache
    dest: /srv/shakenfist/image_cache
    state: link

- name: Create snapshot storage directory
  file:
    path: /srv/shakenfist/replicated/snapshots
    state: directory
    mode: "0755"

- name: Link to snapshot storage directory
  file:
    src: /srv/shakenfist/replicated/snapshots
    dest: /srv/shakenfist/snapshots
    state: link
