# Generated by Django 2.0.13 on 2021-03-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20210311_1730'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubscriptionfilter',
            name='messaging_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.MessagingTemplates'),
        ),
    ]
