# Generated by Django 3.2 on 2021-04-08 06:32

from django.db import migrations, models
import isc_common.fields.files
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0017_auto_20200208_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_1c',
            name='attfile',
            field=isc_common.fields.files.FileFieldEx(blank=True, max_length=255, null=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='files_1c',
            name='mime_type',
            field=isc_common.fields.name_field.NameField(blank=True, null=True, verbose_name='MIME тип файла файла'),
        ),
        migrations.AlterField(
            model_name='files_1c',
            name='real_name',
            field=models.TextField(blank=True, null=True, verbose_name='Первоначальное имя файла'),
        ),
    ]
