# Generated by Django 3.2 on 2021-04-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_c', '0019_auto_20210408_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param_type',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
