[tool.poetry]
name = "gita-api"
version = "0.0.1"
description = "Bhagavad Gita API allows any developer to use content from Bhagavad Gita in their applications."
authors = ["The Gita Initiative <contact@bhagavadgita.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.65.2"
graphene-elastic = "^0.7"
psycopg2-pgevents = "^0.2.2"
SQLAlchemy = "^1.4.19"
uvicorn = "^0.14.0"
graphene-sqlalchemy = "^2.3.0"
graphene-sqlalchemy-filter = "^1.12.2"
python-dotenv = "^0.18.0"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"
black = "^21.6b0"
isort = "^5.9.1"
flake8 = "^3.9.2"
autoflake = "^1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
known_third_party = ["db", "fastapi", "graphene", "models", "pydantic", "pytz", "sqlalchemy", "starlette", "utils"]

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
