[tool.poetry]
name = "django-vehicle-models"
version = "0.1.1"
description = "models for storing in DB"
authors = ["Lamarmora <scheduleanevent@gmail.com>"]
packages = [
    { include = "src/models" }
]
[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
