[tool.poetry]
name = "codemos"
version = "0.1.0"
description = ""
authors = ["Nathanaël <roipoussiere@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.65.2"
Jinja2 = "^3.0.1"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
