# Generated by Django 2.0.13 on 2020-01-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='update_date',
        ),
    ]
