# Generated by Django 2.0.13 on 2020-03-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_news_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Writer'),
        ),
    ]
