# Generated by Django 2.0.13 on 2020-10-08 07:25

import django.db.models.deletion
from django.db import migrations, models

import buildblock.apps.landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_casestudy_casestudypicture_historicalcasestudy_historicalnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('BEFORE', 'BEFORE'), ('AFTER', 'AFTER')], default='BEFORE', max_length=16, verbose_name='Status')),
                ('photo', models.ImageField(upload_to=buildblock.apps.landing.paths.case_study_photo_path, verbose_name='photo')),
                ('case_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='landing.CaseStudy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='casestudypicture',
            name='case_product',
        ),
        migrations.DeleteModel(
            name='CaseStudyPicture',
        ),
    ]
