# Generated by Django 2.0.13 on 2021-03-03 03:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20210216_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinginformation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean')], default='en', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='landingcarousel',
            name='end_date',
            field=models.DateField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='landingcarousel',
            name='start_date',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='landinginformation',
            name='email',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='landinginformation',
            name='telephone',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='landingpopup',
            name='end_date',
            field=models.DateField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='landingpopup',
            name='start_date',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='landingthinbanner',
            name='end_date',
            field=models.DateField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='landingthinbanner',
            name='start_date',
            field=models.DateField(verbose_name='From'),
        ),
    ]
