# Generated by Django 2.0.13 on 2019-08-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(choices=[('land', 'Land'), ('condominium', 'Condominium'), ('multi_family', 'Multi Family'), ('co_op', 'Co-op'), ('townhouse', 'Townhouse'), ('single_family ', 'Single Family')], max_length=64, verbose_name='Product Property Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('GA', 'Georgia'), ('NH', 'New Hampshire'), ('OR', 'Oregon'), ('KY', 'Kentucky'), ('AL', 'Alabama'), ('TX', 'Texas'), ('NC', 'North Carolina'), ('MA', 'Massachusetts'), ('TN', 'Tennessee'), ('SC', 'South Carolina'), ('NY', 'New York'), ('CT', 'Connecticut'), ('NV', 'Nevada'), ('MD', 'Maryland'), ('NJ', 'New Jersey'), ('IL', 'Illinois'), ('ME', 'Maine'), ('NM', 'New Mexico'), ('MN', 'Minnesota'), ('CA', 'California'), ('OK', 'Oklahoma'), ('RI', 'Rhode Island'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('ND', 'North Dakota'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('IN', 'Indiana'), ('DC', 'District of Columbia'), ('VA', 'Virginia'), ('OH', 'Ohio'), ('WV', 'West Virginia'), ('UT', 'Utah'), ('DE', 'Delaware'), ('CO', 'Colorado'), ('FL', 'Florida'), ('VT', 'Vermont'), ('AR', 'Arkansas'), ('MT', 'Montana'), ('MI', 'Michigan'), ('HI', 'Hawaii'), ('MO', 'Missouri'), ('IA', 'Iowa'), ('NE', 'Nebraska'), ('WA', 'Washington'), ('ID', 'Idaho'), ('KS', 'Kansas'), ('MS', 'Mississippi'), ('SD', 'South Dakota'), ('PA', 'Pennsylvania'), ('LA', 'Louisiana')], max_length=16, verbose_name='State'),
        ),
    ]
