# Generated by Django 2.0.13 on 2019-08-13 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20190802_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(choices=[('townhouse', 'Townhouse'), ('multi_family', 'Multi Family'), ('single_family ', 'Single Family'), ('co_op', 'Co-op'), ('land', 'Land'), ('condominium', 'Condominium')], max_length=64, verbose_name='Product Property Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('WA', 'Washington'), ('OR', 'Oregon'), ('MT', 'Montana'), ('CT', 'Connecticut'), ('MI', 'Michigan'), ('SC', 'South Carolina'), ('GA', 'Georgia'), ('UT', 'Utah'), ('WI', 'Wisconsin'), ('ND', 'North Dakota'), ('LA', 'Louisiana'), ('DC', 'District of Columbia'), ('NC', 'North Carolina'), ('CA', 'California'), ('FL', 'Florida'), ('NY', 'New York'), ('ID', 'Idaho'), ('MA', 'Massachusetts'), ('WV', 'West Virginia'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('AZ', 'Arizona'), ('TX', 'Texas'), ('AR', 'Arkansas'), ('VT', 'Vermont'), ('CO', 'Colorado'), ('NJ', 'New Jersey'), ('AK', 'Alaska'), ('NE', 'Nebraska'), ('AL', 'Alabama'), ('MS', 'Mississippi'), ('IL', 'Illinois'), ('PA', 'Pennsylvania'), ('TN', 'Tennessee'), ('KY', 'Kentucky'), ('MN', 'Minnesota'), ('OK', 'Oklahoma'), ('KS', 'Kansas'), ('ME', 'Maine'), ('WY', 'Wyoming'), ('RI', 'Rhode Island'), ('DE', 'Delaware'), ('VA', 'Virginia'), ('HI', 'Hawaii'), ('MD', 'Maryland'), ('OH', 'Ohio'), ('NH', 'New Hampshire'), ('IN', 'Indiana'), ('SD', 'South Dakota'), ('MO', 'Missouri'), ('IA', 'Iowa')], max_length=16, verbose_name='State'),
        ),
    ]
