# Generated by Django 2.0.13 on 2019-08-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190813_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_people',
            field=models.PositiveIntegerField(default=3, verbose_name='The Number of People'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rent',
            field=models.PositiveIntegerField(default=6000, verbose_name='Rent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='property_type',
            field=models.CharField(choices=[('single_family ', 'Single Family'), ('co_op', 'Co-op'), ('townhouse', 'Townhouse'), ('condominium', 'Condominium'), ('multi_family', 'Multi Family'), ('land', 'Land')], max_length=64, verbose_name='Product Property Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('SC', 'South Carolina'), ('NE', 'Nebraska'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('KY', 'Kentucky'), ('WA', 'Washington'), ('AZ', 'Arizona'), ('IA', 'Iowa'), ('AK', 'Alaska'), ('TX', 'Texas'), ('FL', 'Florida'), ('NY', 'New York'), ('DC', 'District of Columbia'), ('NJ', 'New Jersey'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('AR', 'Arkansas'), ('OK', 'Oklahoma'), ('AL', 'Alabama'), ('MI', 'Michigan'), ('SD', 'South Dakota'), ('NH', 'New Hampshire'), ('WY', 'Wyoming'), ('VT', 'Vermont'), ('LA', 'Louisiana'), ('GA', 'Georgia'), ('OR', 'Oregon'), ('IL', 'Illinois'), ('ID', 'Idaho'), ('NV', 'Nevada'), ('NC', 'North Carolina'), ('CO', 'Colorado'), ('ME', 'Maine'), ('KS', 'Kansas'), ('MT', 'Montana'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('CT', 'Connecticut'), ('IN', 'Indiana'), ('RI', 'Rhode Island'), ('NM', 'New Mexico'), ('UT', 'Utah'), ('HI', 'Hawaii'), ('MS', 'Mississippi'), ('CA', 'California'), ('DE', 'Delaware'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('TN', 'Tennessee'), ('PA', 'Pennsylvania'), ('VA', 'Virginia')], max_length=16, verbose_name='State'),
        ),
    ]
