# Generated by Django 2.0.13 on 2019-09-19 06:34

from django.db import migrations, models

import buildblock.apps.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190815_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plan_image',
            field=models.ImageField(blank=True, upload_to=buildblock.apps.product.models.product_plan_path, verbose_name='House Plan Image'),
        ),
    ]
