# Generated by Django 2.0.13 on 2020-05-13 04:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200511_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionwork',
            name='zone_id',
        ),
        migrations.AddField(
            model_name='constructionwork',
            name='zone_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='constructionpicture',
            name='construction_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_picture', to='product.ConstructionWork'),
        ),
        migrations.AlterField(
            model_name='product',
            name='investment_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.InvestmentProduct'),
        ),
    ]
