# Generated by Django 2.0.13 on 2020-05-22 01:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200517_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='constructor',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='constructionpicture',
            name='construction_work',
        ),
        migrations.RemoveField(
            model_name='constructionreport',
            name='construction',
        ),
        migrations.RemoveField(
            model_name='constructionwork',
            name='construction',
        ),
        migrations.RemoveField(
            model_name='constructionwork',
            name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='zone',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='Construction',
        ),
        migrations.DeleteModel(
            name='ConstructionPicture',
        ),
        migrations.DeleteModel(
            name='ConstructionReport',
        ),
        migrations.DeleteModel(
            name='ConstructionWork',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
