# Generated by Django 2.0.13 on 2021-04-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210407_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='lot_sqft',
            field=models.FloatField(default=0, verbose_name='Lot Square Footage'),
        ),
        migrations.AddField(
            model_name='product',
            name='lot_sqft',
            field=models.FloatField(default=0, verbose_name='Lot Square Footage'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='rent',
            field=models.PositiveIntegerField(default=0, verbose_name='Rent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rent',
            field=models.PositiveIntegerField(default=0, verbose_name='Rent'),
        ),
    ]
