# Generated by Django 2.0.13 on 2021-05-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20210416_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rent',
        ),
    ]
