
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-04T23:13:55-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "ce9cdb2a8f6781d2913d3095c948f8bc13079ad5",
 "version": "0.0.10.post.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
