[tool.poetry]
name = "spacy-detok"
version = "0.5.0"
description = "Invert spaCy detokenization"
authors = ["melisa"]

[tool.poetry.dependencies]
python = "^3.8"
transformers = "^4.8.2"
torch = "^1.9.0"
numpy = "^1.21.0"
tqdm = "^4.61.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
