
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-03T06:50:53-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "8fbbe3b71c179f9b4d493a88fe3b366915f823cf",
 "version": "0.0.2b.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
