[tool.poetry]
name = "backwise"
version = "0.1.0"
description = "A Python 3 interface for the Backwise algo-trading software"
authors = ["khunspoonzi <khunspoonzi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytz = "^2021.1"
Unidecode = "^1.2.0"
ccxt = "^1.51.98"
pandas = "1.0.3"
arctic = "^1.79.4"

[tool.poetry.dev-dependencies]
TA-Lib = "^0.4.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
