[tool.poetry]
name = "fast_views"
version = "0.1.0"
description = "Fast operations on time-unit indexed dataframes"
authors = ["peder2911 <pglandsverk@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8"
pandas = "^1.2.5"
numpy = "^1.21.0"

[tool.poetry.dev-dependencies]
jedi = "^0.18.0"
pylint = "^2.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
