
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-02T10:45:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "12d26c57e8e0a65f6415697edbc07fc6e3d06e61",
 "version": "1.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
